version: '3.3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-certs:/etc/ssl/certs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./dist:/usr/share/nginx/html
    networks:
      - nginx-certbot-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx-certs:/etc/letsencrypt
      - ./dist:/usr/share/nginx/html
    entrypoint: >
      certbot certonly --webroot --webroot-path=/usr/share/nginx/html
      -d majabe.so --email your-email@example.com --agree-tos --non-interactive
      --keep-until-expiring --no-eff-email

    depends_on:
      - nginx
    networks:
      - nginx-certbot-network

networks:
  nginx-certbot-network:
    driver: bridge

