version: '3.3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-container
    depends_on:
      - certbot
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-certs:/etc/ssl/certs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./dist:/usr/share/nginx/html
    networks:
      - nginx-certbot-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx-certs:/etc/letsencrypt
      - ./dist:/usr/share/nginx/html
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - nginx-certbot-network

networks:
  nginx-certbot-network:
    driver: bridge

